version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      # Install Snyk
      - npm install -g snyk

      # Authenticate Snyk with your Snyk account
      - snyk auth $SNYK_TOKEN

      # Run Snyk test to check for vulnerabilities
      - snyk test
      - snyk monitor


      # Sync the build artifacts to S3 bucket
      - aws s3 sync build/ s3://${BUCKET_NAME} 

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
