version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - chmod +x run_dependency_check.sh
      - ./run_dependency_check.sh

  post_build:
    commands:
      # Sync the build artifacts to S3 bucket after running the shell script
      - aws s3 sync build/ s3://${BUCKET_NAME}

artifacts:
  files: '**/*'
  base-directory: build
  discard-paths: yes
